export const data = [
  {
    id: '1',
    title: '8 Plots in Ijebu-Ode',
    price: 1000,
    category: 'Land',
    description:
      'Situated on the beautiful banks of the lorem lorem just beside the lorem ipsium, this very lorem piece of land provides you with a beautiful view of the ipsium and a close proximity to the abeokuta airport. Furthermore, this land is siutuat3e near the highway and commercial center of Ogun State',
    address: 'Ijebu-Ode, Ogun State,',
    city: 'Ogun',
    state: 'Ogun',
    image: 'https://angular.io/generated/images/guide/start/app-components.png',
    video: 'https://angular.io/generated/images/guide/start/app-components.png',
    status: 'sold',
    c_of_o: true,
    doxxed: true,
    kyc: true,
  },
  {
    id: '2',
    title: 'Luxury Apartment in Lagos Island',
    price: 2500,
    category: 'Rent',
    description:
      'Beautiful luxury apartment located in the heart of Lagos Island. This apartment features modern amenities and a stunning view of the city skyline.',
    address: 'Lagos Island, Lagos State,',
    city: 'Lagos',
    state: 'Lagos',
    image: 'https://example.com/apartment-image.jpg',
    video: 'https://example.com/apartment-video.mp4',
    status: 'available',
    c_of_o: true,
    doxxed: false,
    kyc: true,
  },
  {
    id: '3',
    title: 'Commercial Space in Ikeja',
    price: 5000,
    category: 'Real Estate',
    description:
      'Spacious commercial space in Ikeja, suitable for various businesses. High foot traffic and excellent visibility.',
    address: 'Ikeja, Lagos State,',
    city: 'Lagos',
    state: 'Lagos',
    image: 'https://example.com/commercial-image.jpg',
    video: 'https://example.com/commercial-video.mp4',
    status: 'available',
    c_of_o: false,
    doxxed: true,
    kyc: false,
  },
  {
    id: '4',
    title: 'Cozy Cottage in Abeokuta',
    price: 800,
    category: 'Land',
    description:
      'Charming cottage nestled in the serene environment of Abeokuta. Perfect for a peaceful retreat surrounded by nature.',
    address: 'Abeokuta, Ogun State,',
    city: 'Abeokuta',
    state: 'Ogun',
    image: 'https://example.com/cottage-image.jpg',
    video: 'https://example.com/cottage-video.mp4',
    status: 'available',
    c_of_o: false,
    doxxed: false,
    kyc: true,
  },
  {
    id: '5',
    title: '8 Plots in Ijebu-Ode ',
    price: 1000,
    category: 'Land',
    description:
      'Situated on the beautiful banks of the lorem lorem just beside the lorem ipsium, this very lorem piece of land provides you with a beautiful view of the ipsium and a close proximity to the abeokuta airport. Furthermore, this land is siutuat3e near the highway and commercial center of Ogun State ',
    address: 'Ijebu-Ode, Ogun State,',
    city: 'Ogun',
    state: 'Ogun',
    image: 'https://angular.io/generated/images/guide/start/app-components.png',
    video: 'https://angular.io/generated/images/guide/start/app-components.png',
    status: 'sold',
    c_of_o: false,
    doxxed: true,
    kyc: true,
  },
  {
    id: '6',
    title: '8 Plots in Ijebu-Ode ',
    price: 1000,
    category: 'Rent',
    description:
      'Situated on the beautiful banks of the lorem lorem just beside the lorem ipsium, this very lorem piece of land provides you with a beautiful view of the ipsium and a close proximity to the abeokuta airport. Furthermore, this land is siutuat3e near the highway and commercial center of Ogun State ',
    address: 'Ijebu-Ode, Ogun State,',
    city: 'Ogun',
    state: 'Ogun',
    image: 'https://angular.io/generated/images/guide/start/app-components.png',
    video: 'https://angular.io/generated/images/guide/start/app-components.png',
    status: 'sold',
    c_of_o: true,
    doxxed: false,
    kyc: true,
  },
  {
    id: '7',
    title: '8 Plots in Ijebu-Ode ',
    price: 1000,
    category: 'Land',
    description:
      'Situated on the beautiful banks of the lorem lorem just beside the lorem ipsium, this very lorem piece of land provides you with a beautiful view of the ipsium and a close proximity to the abeokuta airport. Furthermore, this land is siutuat3e near the highway and commercial center of Ogun State ',
    address: 'Ijebu-Ode, Ogun State,',
    city: 'Ogun',
    state: 'Ogun',
    image: 'https://angular.io/generated/images/guide/start/app-components.png',
    video: 'https://angular.io/generated/images/guide/start/app-components.png',
    status: 'sold',
    c_of_o: true,
    doxxed: true,
    kyc: false,
  },
  {
    id: '8',
    title: '8 Plots in Ijebu-Ode ',
    price: 1000,
    category: 'Real Estate',
    description:
      'Situated on the beautiful banks of the lorem lorem just beside the lorem ipsium, this very lorem piece of land provides you with a beautiful view of the ipsium and a close proximity to the abeokuta airport. Furthermore, this land is siutuat3e near the highway and commercial center of Ogun State ',
    address: 'Ijebu-Ode, Ogun State,',
    city: 'Ogun',
    state: 'Ogun',
    image: 'https://angular.io/generated/images/guide/start/app-components.png',
    video: 'https://angular.io/generated/images/guide/start/app-components.png',
    status: 'sold',
    c_of_o: false,
    doxxed: true,
    kyc: true,
  },
];

export const propertyCategory = ['Land', 'Estate','Rent'];
